# Use the official MongoDB image as the base
FROM mongo:latest

# Optionally, add any additional configuration or setup instructions for your MongoDB image

# Expose the default MongoDB port
EXPOSE 27017

# Optionally, provide a custom entrypoint or command for the MongoDB container

# Start MongoDB
CMD ["mongod"]